### ISSUE TITLE
error from the Github release feed 

### ISSUE THREAD

**Issue by mortendk** [11ty/eleventy-activity-hub#7]
I got an error when trying to grap githubs release notes from a project on. github 

Lets say for the this example the release notes from an exciting Static Site Generator 
```
feed.addSource("atom", "GH eleventy", "https://github.com/11ty/eleventy/releases.atom");
```

Error msg
```
Cannot read properties of undefined (reading 'name') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'name')
[11ty]     at AtomActivity.cleanEntry (file:///Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy-activity-feed/src/AtomActivity.js:27:28)
[11ty]     at file:///Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy-activity-feed/src/Activity.js:68:26
[11ty]     at new Promise (<anonymous>)
[11ty]     at file:///Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy-activity-feed/src/Activity.js:67:11
[11ty]     at Array.map (<anonymous>)
[11ty]     at AtomActivity.getEntries (file:///Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy-activity-feed/src/Activity.js:66:47)
[11ty]     at async ActivityFeed.getEntries (file:///Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy-activity-feed/activityFeed.js:45:8)
[11ty]     at async ActivityFeed.toRssFeed (file:///Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy-activity-feed/activityFeed.js:61:17)
[11ty]     at async Template._render (/Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy/src/TemplateContent.js:473:22)
[11ty]     at async TemplateMap.populateContentDataInMap (/Users/mdk/Web/11tyhub.dev/node_modules/@11ty/eleventy/src/TemplateMap.js:494:13)
```

Did i miss something or is GH just not liking us to grap their release feed ?

**Comment by zachleat** [comment]
Shipping with 1.0.6! GitHub releases have a per-post author rather than a feed-level author and the code didn’t handle it 😭
